camera_intrinsics:          # in pixels
  focal_length: 800         
  delta_x: 0                # x coordinate of principal point
  delta_y: 0                # y coordinate of principal point

transforms:
  baseline_distance: 0.25   # distance between camera and sonar
  plane_distance: 2.0       # distance between camera and object plane
  scale: 1.0                # scale of object/cube
  camera_x_offset: 0.0      # offset of camera in x direction
  camera_y_offset: 0.0      # offset of camera in y direction

sensor_noise_std:           # standard deviation of gaussian noise
  r: 0.01                   # sonar range
  theta: 0.00175            # sonar azimuth angle
  x: 1                      # camera x  
  y: 1                      # camera y

maximum_likelihood:
  method: "Nelder-Mead"     # optimization method
  lambda_values:            # regularization parameter
    - 1.0e+2
    - 1.0e+1
    - 1.0e-1
    - 1.0e-2
    - 1.0e-3
    - 1.0e-4

